### ISSUE TITLE
Deferred error with jedi-0.9.0

### ISSUE THREAD

**Issue by galeo** [tkf/emacs-jedi#228]
After upgrading jedi from 0.8.1 to 0.9.0, I keep getting deferred errors: ```deferred error : (error "\"AttributeError(\\\"'Definition' object has no attribute 'line_nr'\\\",)\"")```.

Here is the epc buffer log when using ```jedi:toggle-log-traceback```:
```
ERROR:epc:AttributeError("'Script' object has no attribute 'get_in_function_call'",)
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/Users/galeo/.emacs.d/elpa/jedi-core-20150422.209/jediepcserver.py", line 90, in get_in_function_call
    call_def = jedi_script(*args).get_in_function_call()
AttributeError: 'Script' object has no attribute 'get_in_function_call'
ERROR:epc:AttributeError("'Definition' object has no attribute 'line_nr'",)
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/handler.py", line 242, in _handle
    reply = handler(uid, *args)
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/utils.py", line 51, in new_method
    ret = method(self, *args, **kwds)
  File "/Users/galeo/.virtualenvs/emacs_jedi_env/lib/python2.7/site-packages/epc/handler.py", line 265, in _handle_call
    return ['return', uid, func(*args)]
  File "/Users/galeo/.emacs.d/elpa/jedi-core-20150422.209/jediepcserver.py", line 171, in defined_names
    return list(map(get_names_recursively, jedi.api.defined_names(*args)))
  File "/Users/galeo/.emacs.d/elpa/jedi-core-20150422.209/jediepcserver.py", line 158, in get_names_recursively
    d = definition_to_dict(definition)
  File "/Users/galeo/.emacs.d/elpa/jedi-core-20150422.209/jediepcserver.py", line 137, in definition_to_dict
    line_nr=d.line_nr,
AttributeError: 'Definition' object has no attribute 'line_nr'
```
It works OK with jedi-0.8.1

**Comment by syohex** [comment]
Sorry late reply.

Would you tell us how to reproduce this issue in more detail ?
I cannot reproduce this issue with simple code.

**Comment by syohex** [comment]
Sorry I can reproduce this issue.
(I did not upgrade jedi)

**Comment by syohex** [comment]
@galeo Thanks for reporting. I have fixed at #230. Please check latest version.

**Comment by galeo** [comment]
@syohex Well done, I have test the latest version with jedi-0.9.0, this error has been fixed. Thanks.

**Comment by syohex** [comment]
There are other issues for jedi 0.9.0. I'll fix them.

**Comment by syohex** [comment]
I fixed for features other than completion at #231.
